name: "godot-ci export"

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
env:
  GODOT_VERSION: 4.2
  EXPORT_NAME: test-project
  TEMPLATE_PATH: /github/home/.local/share/godot/export_templates
  PROJECT_PATH: .
  #          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
  BUTLER_API_KEY: ${{ vars.BUTLER_API_KEY }}

jobs:
  export-web:
    name: Web Export
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.2
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true
      - name: Install Butler
        run: |
          apt-get -y update && apt-get -y install curl unzip
          curl -L -o butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default
          unzip butler.zip
          chmod +x butler
          ./butler -V
          echo $BUTLER_API_KEY
          ./butler login
      - name: Setup
        run: |
          mkdir -vp ${TEMPLATE_PATH}
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ${TEMPLATE_PATH}/${GODOT_VERSION}.stable
      - name: Web Build
        run: |
          mkdir -vp _site
          godot --headless --export-release "Web" _site/index.html
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: export-web
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
