name: "godot-ci export"

permissions:
  contents: read
  pages: write
  id-token: write

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
env:
  GODOT_VERSION: 4.2
  EXPORT_NAME: test-project
  TEMPLATE_PATH: /github/home/.local/share/godot/export_templates
  PROJECT_PATH: .

jobs:
  export-web:
    name: Web Export
    runs-on: ubuntu-latest
    environment: github-pages
    container:
      image: barichello/godot-ci:4.2
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true
      - name: Install Butler
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}

        run: |
          apt-get -y update && apt-get -y install curl unzip
          curl -L -o butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default
          unzip butler.zip
          chmod +x butler
          ./butler -V
          ./butler login
      - name: Setup
        run: |
          mkdir -vp ${TEMPLATE_PATH}
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ${TEMPLATE_PATH}/${GODOT_VERSION}.stable
      - name: Web Build
        run: |
          mkdir -vp _site
          godot --headless --export-release "Web" _site/index.html
      - name: Butler Push
        uses: ./butler push QUBE memeandme/qube:web-final
